// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Jest from "../../node_modules/@glennsl/bs-jest/src/jest.js";
import * as $$Math from "../../src/core/Math.bs.js";

Jest.describe("Math", (function (param) {
        Jest.describe("sq", (function (param) {
                return Jest.test("should square an integer", (function (param) {
                              return Jest.Expect.toEqual(81, Jest.Expect.expect($$Math.sq(9)));
                            }));
              }));
        Jest.describe("sqf", (function (param) {
                return Jest.test("should square a float", (function (param) {
                              return Jest.Expect.toBeSoCloseTo(43.56, 2, Jest.Expect.expect($$Math.sqf(6.6)));
                            }));
              }));
        Jest.describe("pow", (function (param) {
                return Jest.test("should raise base to the exp power", (function (param) {
                              return Jest.Expect.toEqual(100000, Jest.Expect.expect($$Math.pow(10, 5)));
                            }));
              }));
        Jest.describe("lerp", (function (param) {
                return Jest.test("should linear interpolate between integer values", (function (param) {
                              return Jest.Expect.toEqual(12, Jest.Expect.expect($$Math.lerp(5, 25, 0.35)));
                            }));
              }));
        return Jest.describe("lerpf", (function (param) {
                      return Jest.test("should linear interpolate between float values", (function (param) {
                                    return Jest.Expect.toEqual(12, Jest.Expect.expect($$Math.lerpf(5, 25, 0.35)));
                                  }));
                    }));
      }));

var it = Jest.test;

export {
  it ,
  
}
/*  Not a pure module */
