/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const Interpolate_box_shadowBS = require('./Interpolate_box_shadow.bs');

// tslint:disable-next-line:interface-over-type-literal
export type boxShadow = {
  readonly offsetX: string; 
  readonly offsetY: string; 
  readonly blur: string; 
  readonly spread: string; 
  readonly color: string; 
  readonly inset: boolean
};

export const testBoxShadow: (_1:string) => boolean = Interpolate_box_shadowBS.testBoxShadow;

export const parseBoxShadow: (_1:string) => boxShadow = Interpolate_box_shadowBS.parseBoxShadow;

export const remapBoxShadow: (_1:{
  readonly range: [number, number]; 
  readonly domain: [string, string]; 
  readonly value: number
}) => string = function (Arg1: any) {
  const result = Curry._3(Interpolate_box_shadowBS.remapBoxShadow, Arg1.range, Arg1.domain, Arg1.value);
  return result
};
