/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const Interpolate_colorBS = require('./Interpolate_color.bs');

// tslint:disable-next-line:interface-over-type-literal
export type rgba<a> = {
  readonly r: a; 
  readonly g: a; 
  readonly b: a; 
  readonly a: a
};

export const lerpColorRGBA: (_1:{
  readonly acc: rgba<number>; 
  readonly target: rgba<number>; 
  readonly roundness: number
}) => rgba<number> = function (Arg1: any) {
  const result = Curry._3(Interpolate_colorBS.lerpColorRGBA, [Arg1.acc.r, Arg1.acc.g, Arg1.acc.b, Arg1.acc.a], [Arg1.target.r, Arg1.target.g, Arg1.target.b, Arg1.target.a], Arg1.roundness);
  return {r:result[0], g:result[1], b:result[2], a:result[3]}
};

export const remapColor: (_1:{
  readonly range: [number, number]; 
  readonly domain: [rgba<number>, rgba<number>]; 
  readonly value: number
}) => string = function (Arg1: any) {
  const result = Curry._3(Interpolate_colorBS.remapColor, Arg1.range, [[Arg1.domain[0].r, Arg1.domain[0].g, Arg1.domain[0].b, Arg1.domain[0].a], [Arg1.domain[1].r, Arg1.domain[1].g, Arg1.domain[1].b, Arg1.domain[1].a]], Arg1.value);
  return result
};
