/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const Interpolate_unitBS = require('./Interpolate_unit.bs');

// tslint:disable-next-line:interface-over-type-literal
export type cssUnit = { readonly num: number; readonly unit: (null | undefined | string) };

export const testUnit: (_1:string) => boolean = Interpolate_unitBS.testUnit;

export const parseUnit: (_1:string) => cssUnit = Interpolate_unitBS.parseUnit;

export const remapUnit: (_1:{
  readonly range: [number, number]; 
  readonly domain: [string, string]; 
  readonly value: number
}) => string = function (Arg1: any) {
  const result = Curry._3(Interpolate_unitBS.remapUnit, Arg1.range, Arg1.domain, Arg1.value);
  return result
};
