/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const Lerp_colorBS = require('./Lerp_color.bs');

// tslint:disable-next-line:interface-over-type-literal
export type rgba<a> = {
  readonly r: a; 
  readonly g: a; 
  readonly b: a; 
  readonly a: a
};

export const lerpColorRGBA: (_1:{
  readonly acc: rgba<number>; 
  readonly target: rgba<number>; 
  readonly roundness: number
}) => rgba<number> = function (Arg1: any) {
  const result = Curry._3(Lerp_colorBS.lerpColorRGBA, [Arg1.acc.r, Arg1.acc.g, Arg1.acc.b, Arg1.acc.a], [Arg1.target.r, Arg1.target.g, Arg1.target.b, Arg1.target.a], Arg1.roundness);
  return {r:result[0], g:result[1], b:result[2], a:result[3]}
};
