// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Lerp_number from "./Lerp_number.bs.js";

function lerpColorRGBA(acc, target, roundness) {
  return /* record */[
          /* r */Lerp_number.lerpf(acc[/* r */0], target[/* r */0], roundness),
          /* g */Lerp_number.lerpf(acc[/* g */1], target[/* g */1], roundness),
          /* b */Lerp_number.lerpf(acc[/* b */2], target[/* b */2], roundness),
          /* a */Lerp_number.lerpf(acc[/* a */3], target[/* a */3], roundness)
        ];
}

export {
  lerpColorRGBA ,
  
}
/* No side effect */
