// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Utils from "../core/Utils.bs.js";

function lerpf(acc, target, roundness) {
  return (1.0 - roundness) * acc + roundness * target;
}

function lerp(acc, target, roundness) {
  return Utils.iof(lerpf(Utils.foi(acc), Utils.foi(target), roundness));
}

export {
  lerp ,
  lerpf ,
  
}
/* No side effect */
