/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const Lerp_numberBS = require('./Lerp_number.bs');

export const lerp: (_1:{
  readonly acc: number; 
  readonly target: number; 
  readonly roundness: number
}) => number = function (Arg1: any) {
  const result = Curry._3(Lerp_numberBS.lerp, Arg1.acc, Arg1.target, Arg1.roundness);
  return result
};

export const lerpf: (_1:{
  readonly acc: number; 
  readonly target: number; 
  readonly roundness: number
}) => number = function (Arg1: any) {
  const result = Curry._3(Lerp_numberBS.lerpf, Arg1.acc, Arg1.target, Arg1.roundness);
  return result
};
