// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Utils from "../core/Utils.bs.js";

function remapf(param, param$1, value) {
  var dl = param$1[0];
  var rl = param[0];
  return dl + (param$1[1] - dl) * ((value - rl) / (param[1] - rl));
}

function remap(param, param$1, value) {
  return Utils.iof(remapf(/* tuple */[
                  Utils.foi(param[0]),
                  Utils.foi(param[1])
                ], /* tuple */[
                  Utils.foi(param$1[0]),
                  Utils.foi(param$1[1])
                ], Utils.foi(value)));
}

function normalizef(range, value) {
  return remapf(range, /* tuple */[
              0,
              1
            ], value);
}

function normalize(range, value) {
  return remap(range, /* tuple */[
              0,
              1
            ], value);
}

export {
  remapf ,
  remap ,
  normalizef ,
  normalize ,
  
}
/* No side effect */
