// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Math from "../core/Math.bs.js";

function lerpColor(acc, target, roundness) {
  return {
          r: $$Math.lerpf(acc.r, target.r, roundness),
          g: $$Math.lerpf(acc.g, target.g, roundness),
          b: $$Math.lerpf(acc.b, target.b, roundness),
          a: $$Math.lerpf(acc.a, target.a, roundness)
        };
}

function interpolateColor(param, param$1, value) {
  var rl = param[0];
  var progress = (value - rl) / (param[1] - rl);
  var match = lerpColor(param$1[0], param$1[1], progress);
  var rInt = match.r | 0;
  var gInt = match.g | 0;
  var bInt = match.b | 0;
  return "rgba(" + rInt + ", " + gInt + ", " + bInt + ", " + match.a + ")";
}

export {
  lerpColor ,
  interpolateColor ,
  
}
/* No side effect */
