// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Math from "../core/Math.bs.js";
import * as Parse_unit from "../parsers/Parse_unit.bs.js";

function interpolateUnit(param, param$1, value) {
  var rl = param[0];
  var match = Parse_unit.parseUnit(param$1[0]);
  var dlUnit = match.unit;
  var match$1 = Parse_unit.parseUnit(param$1[1]);
  var progress = (value - rl) / (param[1] - rl);
  var output = $$Math.lerpf(match.value, match$1.value, progress);
  if (dlUnit == null) {
    return output.toString();
  } else {
    return output.toString() + dlUnit;
  }
}

export {
  interpolateUnit ,
  
}
/* No side effect */
