// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Math from "../core/Math.bs.js";
import * as Utils from "../core/Utils.bs.js";

function lerpColor(acc, target, roundness) {
  return {
          r: $$Math.lerpf(acc.r, target.r, roundness),
          g: $$Math.lerpf(acc.g, target.g, roundness),
          b: $$Math.lerpf(acc.b, target.b, roundness),
          a: $$Math.lerpf(acc.a, target.a, roundness)
        };
}

function interpolateColor(param, param$1, value) {
  var rl = param[0];
  var progress = (value - rl) / (param[1] - rl);
  var match = lerpColor(param$1[0], param$1[1], progress);
  var rInt = Utils.iof(match.r);
  var gInt = Utils.iof(match.g);
  var bInt = Utils.iof(match.b);
  return "rgba(" + (String(rInt) + (", " + (String(gInt) + (", " + (String(bInt) + (", " + (String(match.a) + ")")))))));
}

export {
  lerpColor ,
  interpolateColor ,
  
}
/* No side effect */
