// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Parse_transform from "../parsers/Parse_transform.bs.js";
import * as Interpolate_unit from "./Interpolate_unit.bs.js";

function interpolateTransform(param, param$1, value) {
  var rh = param[1];
  var rl = param[0];
  var fromTransform = Parse_transform.parseTransform(param$1[0]);
  var toTransform = Parse_transform.parseTransform(param$1[1]);
  var match = fromTransform.transform;
  var match$1 = toTransform.transform;
  var transforms;
  if (match == null) {
    transforms = [];
  } else if (match$1 == null) {
    transforms = [];
  } else {
    var tl_1 = $$Array.map((function (prim) {
            return prim.trim();
          }), match.split(","));
    var th_1 = $$Array.map((function (prim) {
            return prim.trim();
          }), match$1.split(","));
    transforms = $$Array.mapi((function (i, t) {
            return Interpolate_unit.interpolateUnit([
                        rl,
                        rh
                      ], [
                        t,
                        Caml_array.get(th_1, i)
                      ], value);
          }), tl_1);
  }
  return Belt_Option.getWithDefault(Caml_option.nullable_to_opt(fromTransform.transformProperty), "") + ("(" + (transforms.join(", ") + ")"));
}

function interpolateTransforms(range, param, value) {
  var dlTransforms = Parse_transform.parseTransforms(param[0]);
  var dhTransforms = Parse_transform.parseTransforms(param[1]);
  return $$Array.mapi((function (i, t) {
                  return interpolateTransform(range, [
                              t,
                              Caml_array.get(dhTransforms, i)
                            ], value);
                }), dlTransforms).join(" ");
}

export {
  interpolateTransform ,
  interpolateTransforms ,
  
}
/* No side effect */
