// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NormalizeColor from "./normalizeColor";

function testColor(val_) {
  return NormalizeColor.normalizeColor(val_) !== null;
}

function parseColor(val_) {
  return NormalizeColor.rgba(val_);
}

export {
  testColor ,
  parseColor ,
  
}
/* ./normalizeColor Not a pure module */
