// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var onlyNumericRe = /[\d.]/g;

function testNumber(val_) {
  if (isNaN(parseFloat(val_))) {
    return false;
  } else {
    return onlyNumericRe.test(val_);
  }
}

function parseNumber(val_) {
  return parseFloat(val_);
}

export {
  testNumber ,
  parseNumber ,
  
}
/* No side effect */
