// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NormalizeColor from "./normalize-color";

function testColor(val_) {
  return NormalizeColor.normalizeColor(val_) !== null;
}

function parseColor(val_) {
  return NormalizeColor.rgba(val_);
}

export {
  testColor ,
  parseColor ,
  
}
/* ./normalize-color Not a pure module */
