/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Parse_numberBS = require('./Parse_number.bs');

export const testNumber: (_1:string) => boolean = Parse_numberBS.testNumber;

export const parseNumber: (_1:string) => number = Parse_numberBS.parseNumber;
