// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vector from "../core/Vector.bs.js";

function applyForce(force, entity, time) {
  var nextAcceleration = Vector.divf(force, entity.mass);
  var nextVelocity = Vector.addf(entity.velocity, Vector.multf(nextAcceleration, time));
  var nextPosition = Vector.addf(entity.position, Vector.multf(nextVelocity, time));
  return {
          mass: entity.mass,
          acceleration: nextAcceleration,
          velocity: nextVelocity,
          position: nextPosition
        };
}

export {
  applyForce ,
  
}
/* No side effect */
