// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Vector from "../core/Vector.bs.js";

function applyForce(force, entity) {
  var nextAcceleration = Vector.divf(force, entity[/* mass */0]);
  var nextVelocity = Vector.addf(entity[/* velocity */2], nextAcceleration);
  var nextPosition = Vector.addf(entity[/* position */3], nextVelocity);
  return /* record */[
          /* mass */entity[/* mass */0],
          /* acceleration */nextAcceleration,
          /* velocity */nextVelocity,
          /* position */nextPosition
        ];
}

export {
  applyForce ,
  
}
/* No side effect */
