/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const ForceBS = require('./Force.bs');

import {t as Vector_t} from '../../src/core/Vector.gen';

// tslint:disable-next-line:interface-over-type-literal
export type entity = {
  readonly acceleration: Vector_t<number>; 
  readonly velocity: Vector_t<number>; 
  readonly position: Vector_t<number>
};
export type Entity = entity;

export const applyForce: (_1:{
  readonly force: Vector_t<number>; 
  readonly moverMass: number; 
  readonly acceleration: Vector_t<number>; 
  readonly velocity: Vector_t<number>; 
  readonly position: Vector_t<number>
}) => entity = function (Arg1: any) {
  const result = Curry._5(ForceBS.applyForce, Arg1.force, Arg1.moverMass, Arg1.acceleration, Arg1.velocity, Arg1.position);
  return {acceleration:result[0], velocity:result[1], position:result[2]}
};
