// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Vector from "../core/Vector.bs.js";

function frictionForceV(mu, $staropt$star, velocity, param) {
  var normal = $staropt$star !== undefined ? $staropt$star : 1;
  var mag = mu * normal;
  var dir = Vector.normf(Vector.multf(velocity, -1));
  return Vector.multf(dir, mag);
}

export {
  frictionForceV ,
  
}
/* No side effect */
