/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const FrictionBS = require('./Friction.bs');

import {t as Vector_t} from '../../src/core/Vector.gen';

export const frictionForceV: (_1:{
  readonly mu: number; 
  readonly normal?: number; 
  readonly velocity: Vector_t<number>
}, _2:void) => Vector_t<number> = function (Arg1: any, Arg2: any) {
  const result = Curry._4(FrictionBS.frictionForceV, Arg1.mu, Arg1.normal, Arg1.velocity, Arg2);
  return result
};
