/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const GravityBS = require('./Gravity.bs');

import {t as Vector_t} from '../../src/core/Vector.gen';

export const g: number = GravityBS.g;

export const force: (_1:{
  readonly m1: number; 
  readonly m2: number; 
  readonly r: number
}) => number = function (Arg1: any) {
  const result = Curry._3(GravityBS.force, Arg1.m1, Arg1.m2, Arg1.r);
  return result
};

export const forceV: (_1:{
  readonly m1: number; 
  readonly m2: number; 
  readonly v1: Vector_t<number>; 
  readonly v2: Vector_t<number>
}) => Vector_t<number> = function (Arg1: any) {
  const result = Curry._4(GravityBS.forceV, Arg1.m1, Arg1.m2, Arg1.v1, Arg1.v2);
  return result
};
