// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Math from "../core/Math.bs.js";
import * as Vector from "../core/Vector.bs.js";

var gU = 6.67428 * Math.pow(10, -11);

function gravityForceMag(attractorMass, moverMass, r, gOpt, param) {
  var g = gOpt !== undefined ? gOpt : gU;
  return g * attractorMass * moverMass / Math.pow(r, 2);
}

function gravityForceV(attractorMass, moverMass, attractor, mover, gOpt, threshold, param) {
  var g = gOpt !== undefined ? gOpt : gU;
  var v = Vector.subf(attractor, mover);
  var mag = Vector.magf(v);
  var distance;
  if (threshold !== undefined) {
    var th = threshold;
    distance = $$Math.constrainf(th[0], th[1], mag);
  } else {
    distance = mag;
  }
  var dir = Vector.normf(v);
  return Vector.multf(dir, gravityForceMag(attractorMass, moverMass, distance, g, /* () */0));
}

var gE = 9.80665;

export {
  gU ,
  gE ,
  gravityForceMag ,
  gravityForceV ,
  
}
/* gU Not a pure module */
