/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const GravityBS = require('./Gravity.bs');

import {t as Vector_t} from '../../src/core/Vector.gen';

export const g: number = GravityBS.g;

export const force: (_1:{
  readonly attractorMass: number; 
  readonly moverMass: number; 
  readonly r: number
}) => number = function (Arg1: any) {
  const result = Curry._3(GravityBS.force, Arg1.attractorMass, Arg1.moverMass, Arg1.r);
  return result
};

export const forceV: (_1:{
  readonly attractorMass: number; 
  readonly moverMass: number; 
  readonly attractor: Vector_t<number>; 
  readonly mover: Vector_t<number>
}) => Vector_t<number> = function (Arg1: any) {
  const result = Curry._4(GravityBS.forceV, Arg1.attractorMass, Arg1.moverMass, Arg1.attractor, Arg1.mover);
  return result
};
