// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Math from "../core/Math.bs.js";
import * as Vector from "../core/Vector.bs.js";

var g = 6.67428 * $$Math.pow(10, -11);

function force(attractorMass, moverMass, r) {
  return g * attractorMass * moverMass / $$Math.sqf(r);
}

function forceV(attractorMass, moverMass, attractor, mover) {
  var v = Vector.subf(attractor, mover);
  var mag = Vector.magf(v);
  var dir = Vector.normf(v);
  return Vector.multf(dir, force(attractorMass, moverMass, mag));
}

export {
  g ,
  force ,
  forceV ,
  
}
/* g Not a pure module */
