// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.bs.js";
import * as Caml_int32 from "bs-platform/lib/es6/caml_int32.js";

function sq(x) {
  return Caml_int32.imul(x, x);
}

function sqf(x) {
  return x * x;
}

function pow(base, exp) {
  if (exp !== 0) {
    if (exp !== 1) {
      if (exp < 0) {
        return 1 / Utils.foi(base) * pow(base, exp + 1 | 0);
      } else {
        return Utils.foi(base) * pow(base, exp - 1 | 0);
      }
    } else {
      return Utils.foi(base);
    }
  } else {
    return 1;
  }
}

function lerpf(acc, target, roundness) {
  return (1.0 - roundness) * acc + roundness * target;
}

function lerp(acc, target, roundness) {
  return Utils.iof(lerpf(Utils.foi(acc), Utils.foi(target), roundness));
}

export {
  sq ,
  sqf ,
  pow ,
  lerp ,
  lerpf ,
  
}
/* No side effect */
