// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.bs.js";
import * as Caml_int32 from "bs-platform/lib/es6/caml_int32.js";

function sq(x) {
  return Caml_int32.imul(x, x);
}

function sqf(x) {
  return x * x;
}

function lerpf(acc, target, roundness) {
  return (1.0 - roundness) * acc + roundness * target;
}

function lerp(acc, target, roundness) {
  return Utils.iof(lerpf(acc, target, roundness));
}

export {
  sq ,
  sqf ,
  lerp ,
  lerpf ,
  
}
/* No side effect */
