/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const MathBS = require('./Math.bs');

export const constrain: (_1:{ readonly low: number; readonly high: number }, _2:number) => number = function (Arg1: any, Arg2: any) {
  const result = Curry._3(MathBS.constrain, Arg1.low, Arg1.high, Arg2);
  return result
};
