/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const UtilsBS = require('./Utils.bs');

export const foi: (_1:number) => number = UtilsBS.foi;

export const iof: (_1:number) => number = UtilsBS.iof;
