// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_builtin_exceptions from "bs-platform/lib/es6/caml_builtin_exceptions.js";

function foi(prim) {
  return prim;
}

function iof(prim) {
  return prim | 0;
}

function scanf(reducer, init) {
  var state = /* record */[
    /* accumulator */init,
    /* reducer */reducer,
    /* listener */(function (param) {
        if (param !== 0) {
          throw [
                Caml_builtin_exceptions.match_failure,
                /* tuple */[
                  "Utils.re",
                  16,
                  65
                ]
              ];
        } else {
          return /* () */0;
        }
      })
  ];
  var start = function (listener) {
    state[/* listener */2] = listener;
    return /* () */0;
  };
  var next = function (value) {
    state[/* accumulator */0] = Curry._2(reducer, state[/* accumulator */0], value);
    return Curry._1(state[/* listener */2], state[/* accumulator */0]);
  };
  return /* record */[
          /* start */start,
          /* next */next
        ];
}

export {
  foi ,
  iof ,
  scanf ,
  
}
/* No side effect */
