// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function foi(prim) {
  return prim;
}

function iof(prim) {
  return prim | 0;
}

function sof(prim) {
  return prim.toString();
}

function $$parseFloat$1(prim) {
  return parseFloat(prim);
}

export {
  foi ,
  iof ,
  sof ,
  $$parseFloat$1 as $$parseFloat,
  
}
/* No side effect */
