// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function foi(prim) {
  return prim;
}

function iof(prim) {
  return prim | 0;
}

function sof(prim) {
  return prim.toString();
}

export {
  foi ,
  iof ,
  sof ,
  
}
/* No side effect */
