name: renature CI

on:
  push:
    branches:
      - saturn
  pull_request:
    branches:
      - saturn

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile --non-interactive
      - name: Build ReScript and Test
        run: |
          yarn build:res
          yarn test
      - name: Check TypeScript
        run: yarn check:ts
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build

  docs:
    # TODO: Switch to `ubuntu-latest` when GH internal migration complete
    # because it has awscli@2 built in.
    # See `ubuntu-latest` note in: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: AWS CLI version
        run: "aws --version"
      - name: Install Dependencies
        run: yarn --frozen-lockfile --non-interactive
      - name: Quality checks
        run: yarn run check-ci
      - name: Build docs
        run: |
          yarn run clean
          yarn run build

      - name: Deploy docs (staging)
        if: github.ref != 'refs/heads/saturn'
        run: yarn run deploy:stage
        env:
          FORMIDEPLOY_GIT_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_DEPLOYMENT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Deploy docs (production)
        if: github.ref == 'refs/heads/saturn'
        run: yarn run deploy:prod
        env:
          GITHUB_DEPLOYMENT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
