name: renature CI
on:
  push:
    branches:
      - saturn
  pull_request:
    branches:
      - saturn
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile --non-interactive
      - name: Build ReScript and Test
        run: |
          yarn build:res
          yarn test
      - name: Check TypeScript
        run: yarn check:ts
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
